### PR TITLE
chore: deploy more chains on TheGraph decentralized network

### PR DESCRIPTION
**Pull request by alexandre-abrioux**
This PR adds five new URLs and modifies two existing URLs for our payment subgraphs.

### Added Chains

Those chains were deployed on TheGraph decentralized network:
- `matic`
- `arbitrum-one`
- `avalanche`
- `fantom`
- `celo`

### Modified Chains
Those chains were migrated from the (now deprecated) Ethereum-based decentralized network to the newer Arbitrum-based decentralized network ([see announcement](https://thegraph.com/docs/en/arbitrum/arbitrum-faq/)):
- `gnosis`
- `mainnet` (ethereum)

### CODE REVIEW

**Review by yomarion — APPROVED** [review]

**Comment by MantisClone** [comment]
### Questions
@alexandre-abrioux 
1. Can you elaborate more about what "migrating" means for the `gnosis` and `mainnet` deployments on the Ethereum-based decentralized network? The announcement states that the Ethereum-based decentralized network and the Arbitrum-based decentralized network will operate in parallel for now.
2. Should we retain the link to the Ethereum-based decentralized network deployments for `gnosis` and `mainnet` in the README?

According to the [announcement](https://thegraph.com/docs/en/arbitrum/arbitrum-faq/#will-existing-subgraphs-on-ethereum-continue-to-work):
> ### Will existing subgraphs on Ethereum continue to work?
> Yes, The Graph Network contracts will operate in parallel on both Ethereum and Arbitrum until moving fully to Arbitrum at a later date.

**Review by MantisClone — COMMENTED** [review]
Please see my comment above.

**Comment by alexandre-abrioux** [comment]
@MantisClone Thanks, regarding your questions:

> Can you elaborate more about what "migrating" means for the gnosis and mainnet deployments on the Ethereum-based decentralized network? The announcement states that the Ethereum-based decentralized network and the Arbitrum-based decentralized network will operate in parallel for now.

There is no specific date for this deprecation (because of its decentralized nature), but as time goes by, there should be fewer indexers watching the Ethereum-based decentralized network, so it is safer to migrate as soon as possible to guarantee the best SLA. It is also less costly for us to manage the subgraphs (update and curate) on Arbitrum than it is on Ethereum.

> Should we retain the link to the Ethereum-based decentralized network deployments for gnosis and mainnet in the README?

Unfortunately, no, we cannot. Once a subgraph is migrated, old URLs are only guaranteed to work for 48 hours after the migration, but there is no guarantee after that; see [this FAQ](https://thegraph.com/docs/en/arbitrum/l2-transfer-tools-faq/#what-happens-to-the-ethereum-mainnet-version-of-my-subgraph-after-i-transfer-to-arbitrum). Even if it were possible, it would have been costly to keep curating/signaling both subgraphs at the same time so not really worth it IMO.

**Comment by MantisClone** [comment]
@alexandre-abrioux Thank you for your answers! All questions resolved :+1:

**Review by MantisClone — APPROVED** [review]

**Pull request merged**
